---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - nginx_install
        - nginx_configure
        - nginx_run
  tags:
    - nginx_install
    - nginx_configure
    - nginx_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - nginx_install
  tags:
    - nginx_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - nginx_configure
  tags:
    - nginx_configure

- name: Ensure nginx service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ __nginx_systemd_service }}"
    state: started
    enabled: true

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
