---
namespace: fmjstudios
name: webservers
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for server setup and configuration
license_file: "LICENSE"
tags:
  - webserver
  - http
  - https
  - websocket
  - tls
  - ssl
  - apache
  - nginx
  - caddy
dependencies:
  community.crypto: ">=2.14.0"
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github