---
- name: configure-Debian | Configure apache's ports.conf
  ansible.builtin.lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ __apache__.regexp }}"
    line: "{{ __apache__.line }}"
    state: present
    mode: 0644
  loop: "{{ apache_ports_configuration_items }}"
  loop_control:
    loop_var: __apache__
  notify: Restart apache

- name: configure-Debian | Enable apache modifications
  ansible.builtin.file:
    src: "{{ apache_server_root }}/mods-available/{{ __apache__ }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ __apache__ }}"
    state: link
    mode: 0644
  loop: "{{ apache_mods_enabled }}"
  loop_control:
    loop_var: __apache__
  notify: Restart apache

- name: configure-Debian | Disable apache modifications
  ansible.builtin.file:
    path: "{{ apache_server_root }}/mods-enabled/{{ __apache__ }}"
    state: absent
  loop: "{{ apache_mods_disabled }}"
  loop_control:
    loop_var: __apache__
  notify: Restart apache

- name: configure-Debian | Check whether certificates defined in vhosts exist
  ansible.builtin.stat:
    path: "{{ __apache__.certificate_file }}"
  register: apache_ssl_certificates
  loop: "{{ apache_vhosts_ssl }}"
  loop_control:
    loop_var: __apache__

- name: configure-Debian | Ensure document roots are existent and correctly configured
  ansible.builtin.file:
    path: "{{ __apache__.documentroot }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  loop: "{{ apache_vhosts_ssl }}"
  loop_control:
    loop_var: __apache__

- name: configure-Debian | Configure apache vhosts
  ansible.builtin.template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart apache
  when: apache_create_vhosts | bool

- name: configure-Debian | Add virtual host symlink in sites-enabled
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
    mode: 0644
  notify: Restart apache
  when: apache_create_vhosts | bool

- name: configure-Debian | Remove default virtual host in sites-enabled
  ansible.builtin.file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhosts_filename }}"
    state: absent
  notify: Restart apache
  when: apache_remove_default_vhost | bool
